### PR TITLE
draft-charter

### PR DESCRIPTION
**Pull request by hythloda**
Don't you hate when there is a type in the branch name :) 
Here is the charter that is mentioned in #1

### CODE REVIEW

**Comment by mlieberman85** [comment]
@mihaimaruseac @lumjjb @pxp928 @SantiagoTorres @jeffmendoza can you all Give a +1 here?

**Comment by mihaimaruseac** [comment]
+1 from me, thank you for making this

**Review by pxp928 — APPROVED** [review]
+1

**Review by jeffmendoza — APPROVED** [review]
+1

**Comment by hythloda** [comment]
@lumjjb @SantiagoTorres Think we are only missing you.

**Pull request merged**
